import { expect, test } from "@playwright/test";

test("confirmation, cancellation, retry, permanent deletion, counts and CSV", async ({ page }, testInfo) => {
  await page.goto("/admin/login");
  expect((await page.request.delete(`/api/admin/registrations/registration.${"a".repeat(64)}`, { headers: { origin: "http://127.0.0.1:3100" } })).status()).toBe(401);
  await page.getByLabel("Username", { exact: true }).fill("fixture-admin");
  await page.getByLabel("Password", { exact: true }).fill("Synthetic password 2026!");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page).toHaveURL(/\/admin$/, { timeout: 30000 });
  const before = await (await page.request.get("/api/admin/stats")).json();
  await page.goto("/admin/registrations");
  const email = `delete-${testInfo.project.name}@example.test`;
  // Each viewport gets its own document; test-only requests use the real public endpoint.
  const challenge = await (await page.request.get("/api/registrations")).json();
  await page.waitForTimeout(3100);
  const saved = await page.request.post("/api/registrations", { headers: { origin: "http://127.0.0.1:3100" }, data: { fullName: "Delete Test Student", grade: "Grade 11", email, phone: "+15550102030", area: "Finance", motivation: "Synthetic applicant for permanent deletion workflow testing.", speakerQuestion: "How do banks evaluate lending risk?", website: "", formToken: challenge.formToken } });
  expect(saved.status()).toBe(201);
  await page.getByRole("searchbox").fill(email);
  await page.getByLabel("Filter by status").selectOption("Pending");
  await page.getByLabel("Filter by grade").selectOption("Grade 11");
  await page.getByLabel("Filter by area").selectOption("Finance");
  await expect(page.locator(".admin-pagination > span")).toHaveText("1-1 of 1");
  const listing = await (await page.request.get(`/api/admin/registrations?search=${email}`)).json(); const id = listing.items[0]._id;
  await page.getByRole("button", { name: /Delete Test Student/ }).click();
  const detail = page.getByRole("dialog", { name: "Delete Test Student", exact: true });
  const trigger = detail.getByRole("button", { name: "Delete registration", exact: true });
  await trigger.click(); const confirmation = page.getByRole("dialog", { name: "Delete registration?", exact: true });
  await expect(confirmation).toContainText("Delete Test Student");
  await expect(confirmation.getByRole("button", { name: "Cancel", exact: true })).toBeFocused();
  await page.keyboard.press("Escape"); await expect(confirmation).not.toBeVisible(); await expect(trigger).toBeFocused();
  expect((await page.request.get(`/api/admin/registrations/${id}`)).status()).toBe(200);
  await trigger.click(); await confirmation.getByRole("button", { name: "Cancel", exact: true }).click(); await expect(trigger).toBeFocused();
  await trigger.click();
  let deleteRequests = 0;
  await page.route(`**/api/admin/registrations/${id}`, async route => {
    if (route.request().method() !== "DELETE") return route.continue();
    deleteRequests++;
    if (deleteRequests === 1) return route.fulfill({ status: 500, contentType: "application/json", body: JSON.stringify({ ok: false, error: "DELETE_FAILED" }) });
    await new Promise(resolve => setTimeout(resolve, 200)); await route.continue();
  });
  await confirmation.getByRole("button", { name: "Delete permanently" }).click();
  await expect(confirmation.getByRole("alert")).toHaveText("Could not delete this registration. Please try again.");
  await expect(detail).toBeVisible(); expect((await page.request.get(`/api/admin/registrations/${id}`)).status()).toBe(200);
  await confirmation.screenshot({ path: testInfo.outputPath("delete-confirmation.png") });
  await confirmation.getByRole("button", { name: "Delete permanently" }).click();
  await expect(confirmation.getByRole("button", { name: "Deleting" })).toBeDisabled();
  await expect(confirmation).not.toBeVisible(); await expect(detail).not.toBeVisible();
  await expect(page.locator(".admin-notice[role=status]")).toHaveText("Registration deleted.");
  await expect(page.getByText("No matching applications")).toBeVisible();
  await expect(page.getByRole("searchbox")).toHaveValue(email);
  for (const [label, value] of [["Filter by status", "Pending"], ["Filter by grade", "Grade 11"], ["Filter by area", "Finance"]]) await expect(page.getByLabel(label)).toHaveValue(value);
  expect(deleteRequests).toBe(2);
  expect((await page.request.get(`/api/admin/registrations/${id}`)).status()).toBe(404);
  const after = await (await page.request.get("/api/admin/stats")).json();
  expect(after).toMatchObject({ total: before.total, pending: before.pending, accepted: before.accepted, declined: before.declined });
  expect(await (await page.request.get("/api/admin/export")).text()).not.toContain(email);
  await page.reload(); await page.getByRole("searchbox").fill(email); await expect(page.getByText("No matching applications")).toBeVisible();
  await page.goto("/admin"); await expect(page.locator(".admin-metric").first().locator("strong")).toHaveText(String(before.total));
});
